---
- name: install Samba4 because Windows 10 no longer support SMB1 protocol
  yum:
    name: samba4

- name: enable Samba on boot
  service:
    name: smb
    enabled: yes

- name: set wrokgroup for Samba
  replace:
    path: /etc/samba/smb.conf
    regexp: ^\s.workgroup\s.=\s.*.
    replace: "        workgroup = WORKGROUP"
  notify: restart samba

- name: get current DocumentRoot
  shell: grep "^DocumentRoot" /etc/httpd/conf/httpd.conf | awk '{print $2}' | sed -e 's/^"//' -e 's/"$//'
  ignore_errors: yes
  register: current_document_root

- name: set Samba config for workspace
  template:
    src: smb.conf.workspace.j2
    dest: /etc/samba/smb.conf.workspace
    owner: root
    group: root
    mode: 0644

- name: add share directory setting for Samba
  blockinfile:
    path: /etc/samba/smb.conf
    block: |
      include = /etc/samba/smb.conf.workspace
  notify: restart samba

- name: register Smaba user
  shell: "echo -e \"{{ samba_user_password }}\n{{ samba_user_password }}\" | pdbedit -a -t -u {{ roles_common_deploy_user }}"
  notify: restart samba
